const exampleData = [
  {
    "Venue": "Alamo Drafthouse New Mission",
    "Series": "",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "6:30 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Sorry To Bother You",
    "Director": "Boots Riley",
    "Year": 2018,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "Alamo Drafthouse New Mission",
    "Series": "",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "9:25 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Sorry To Bother You",
    "Director": "Boots Riley",
    "Year": 2018,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "Balboa Theatre",
    "Series": "Popcorn Palace",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "10:00 AM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Spirited Away",
    "Director": "Hayao Miyazaki",
    "Year": "",
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "BAMPFA",
    "Series": "Bergman 100: A Summer Interlude",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "5:00 PM",
    "TRT": 84,
    "Format": "DCP",
    "Note": "",
    "Film": "Brink of Life",
    "Director": "Ingmar Bergman",
    "Year": 1958,
    "RATIO": "",
    "Country": "Sweden",
    "Language": "Swedish",
    "tmdb": ""
  },
  {
    "Venue": "BAMPFA",
    "Series": "Aki Kaurismäki: Films from the Other Side of Hope",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "7:00 PM",
    "TRT": 97,
    "Format": "",
    "Note": "",
    "Film": "The Man Without a Past",
    "Director": "Aki Kaurismäki",
    "Year": 2002,
    "RATIO": "",
    "Country": "Finland, France, Germany",
    "Language": "Finnish",
    "tmdb": ""
  },
  {
    "Venue": "Castro Theater",
    "Series": "Double Feature",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "1:30 PM",
    "TRT": 127,
    "Format": "DCP",
    "Note": "",
    "Film": "20,000 Leagues Under the Sea",
    "Director": "Richard Fleischer",
    "Year": 1954,
    "RATIO": "Scope",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Castro Theater",
    "Series": "Double Feature",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "3:50 PM",
    "TRT": 104,
    "Format": "DCP",
    "Note": "",
    "Film": "Jason and the Argonauts",
    "Director": "Don Chaffey",
    "Year": 1963,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Castro Theater",
    "Series": "Yellow Submarine 50th Anniversary",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "6:00 PM",
    "TRT": 85,
    "Format": "DCP",
    "Note": "50th Anniversary 4K Restoration",
    "Film": "Yellow Submarine",
    "Director": "George Dunning",
    "Year": 1968,
    "RATIO": "",
    "Country": "United Kingdom",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "Castro Theater",
    "Series": "Yellow Submarine 50th Anniversary",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "8:00 PM",
    "TRT": 85,
    "Format": "DCP",
    "Note": "50th Anniversary 4K Restoration",
    "Film": "Yellow Submarine",
    "Director": "George Dunning",
    "Year": 1968,
    "RATIO": "",
    "Country": "United Kingdom",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "2:15 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "A Jitney Elopement",
    "Director": "",
    "Year": 1915,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "11:30 AM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "A Night Out",
    "Director": "",
    "Year": 1915,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "1:45 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "In The Park",
    "Director": "",
    "Year": 1915,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "12:15 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "The Champion",
    "Director": "",
    "Year": 1915,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "3:00 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "The Tramp",
    "Director": "",
    "Year": 1915,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Niles Essanay Silent Film Museum",
    "Series": "Charlie Chaplin Days",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "3:45 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "When The Movies Came from Niles",
    "Director": "",
    "Year": 1964,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Roxie Theater",
    "Series": "",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "6:30 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Ava",
    "Director": "Sadaf Foroughi",
    "Year": 2017,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Roxie Theater",
    "Series": "",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "1:30 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Jim Gaffigan: Noble Ape",
    "Director": "Jeannie Gaffigan",
    "Year": "",
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Roxie Theater",
    "Series": "",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "8:45 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Jim Gaffigan: Noble Ape",
    "Director": "Jeannie Gaffigan",
    "Year": "",
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Roxie Theater",
    "Series": "MiDNiTES FOR MANiACS",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "9:30 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "Double Feature with Milk",
    "Film": "Mala Noche",
    "Director": "Gus Van Sant",
    "Year": 1988,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "Roxie Theater",
    "Series": "MiDNiTES FOR MANiACS",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "7:00 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "10 Year Anniversary, Double Feature with Mala Noche",
    "Film": "Milk",
    "Director": "Gus Van Sant",
    "Year": 2008,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "SF MOMA",
    "Series": "Black Powers: Reframing Hollywood",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "1:00 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Eve's Bayou",
    "Director": "Kasi Lemmons",
    "Year": 1997,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "SF MOMA",
    "Series": "Black Powers: Reframing Hollywood",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "4:00 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Losing Ground",
    "Director": "Kathleen Collins",
    "Year": 1982,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "SF MOMA",
    "Series": "Black Powers: Reframing Hollywood",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "6:30 PM",
    "TRT": "",
    "Format": "",
    "Note": "",
    "Film": "Love Jones",
    "Director": "Theodore Witcher",
    "Year": 1997,
    "RATIO": "",
    "Country": "",
    "Language": "",
    "tmdb": ""
  },
  {
    "Venue": "The Stanford Theater",
    "Series": "Summer 2018",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "5:45 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "",
    "Film": "The Thin Man",
    "Director": "W. S. Van Dyke",
    "Year": 1934,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "The Stanford Theater",
    "Series": "Summer 2018",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "9:25 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "",
    "Film": "The Thin Man",
    "Director": "W. S. Van Dyke",
    "Year": 1934,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "The Stanford Theater",
    "Series": "Summer 2018",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "3:50 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "",
    "Film": "Top Hat",
    "Director": "Mark Sandrich",
    "Year": 1935,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  },
  {
    "Venue": "The Stanford Theater",
    "Series": "Summer 2018",
    "Link": "",
    "Date": "07/15/2018",
    "Showtime": "7:30 PM",
    "TRT": "",
    "Format": "35mm",
    "Note": "",
    "Film": "Top Hat",
    "Director": "Mark Sandrich",
    "Year": 1935,
    "RATIO": "",
    "Country": "USA",
    "Language": "English",
    "tmdb": ""
  }
]

const tomorrow = [  {
  "Venue": "BAMPFA",
  "Series": "Jacques Becker",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "6:00 PM",
  "TRT": 110,
  "Format": "35mm",
  "Note": "Imported Print",
  "Film": "Goupi mains-rouges",
  "Director": "Jacques Becker",
  "Year": 1943,
  "RATIO": "",
  "Country": "France",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "BAMPFA",
  "Series": "Michelangelo Antonioni",
  "Link": "https://bampfa.org/event/le-amiche-5",
  "Date": "07/14/2018",
  "Showtime": "8:00 PM",
  "TRT": 104,
  "Format": "35mm",
  "Note": "Imported Print",
  "Film": "Le Amiche",
  "Director": "Michelangelo Antonioni",
  "Year": "",
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Niles Essanay Silent Film Museum",
  "Series": "Charlie Chaplin Days",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "1:15 PM",
  "TRT": "",
  "Format": "",
  "Note": "with audio commentary by Dan Kamin",
  "Film": "One A.M.",
  "Director": "",
  "Year": 1915,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Niles Essanay Silent Film Museum",
  "Series": "Charlie Chaplin Days",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "12:30 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "The Champion",
  "Director": "",
  "Year": 1915,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Niles Essanay Silent Film Museum",
  "Series": "Charlie Chaplin Days",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "7:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "Judy Rosenberg (piano) \\n Preceded by shorts: Chaplin’s Flea Circus (1921), A Night at the Show (1915, Essanay, Los Angeles)",
  "Film": "The Kid",
  "Director": "",
  "Year": 1921,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Niles Essanay Silent Film Museum",
  "Series": "Charlie Chaplin Days",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "2:45 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "The Movies Go West",
  "Director": "",
  "Year": 1974,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Niles Essanay Silent Film Museum",
  "Series": "Charlie Chaplin Days",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "3:15 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "The Tramp",
  "Director": "",
  "Year": 1915,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Roxie Theater",
  "Series": "",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "7:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Ava",
  "Director": "Sadaf Foroughi",
  "Year": 2017,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Roxie Theater",
  "Series": "",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "5:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Jim Gaffigan: Noble Ape",
  "Director": "Jeannie Gaffigan",
  "Year": "",
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Roxie Theater",
  "Series": "",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "4:30 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Perdida",
  "Director": "Viviana García-Besné",
  "Year": 2009,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "Roxie Theater",
  "Series": "",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "7:00 PM",
  "TRT": 70,
  "Format": "",
  "Note": "",
  "Film": "Santo Contra Cerebro Del Mal",
  "Director": "Joselito Rodriguez",
  "Year": 1961,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "SF MOMA",
  "Series": "Black Powers: Reframing Hollywood",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "4:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Do the Right Thing",
  "Director": "Spike Lee",
  "Year": 1989,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "SF MOMA",
  "Series": "Black Powers: Reframing Hollywood",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "1:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Killer of Sheep",
  "Director": "Charles Burnett",
  "Year": 1978,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "SF MOMA",
  "Series": "Black Powers: Reframing Hollywood",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "7:00 PM",
  "TRT": "",
  "Format": "",
  "Note": "",
  "Film": "Medicine for Melancholy",
  "Director": "Barry Jenkins",
  "Year": 2008,
  "RATIO": "",
  "Country": "",
  "Language": "",
  "tmdb": ""
  },
  {
  "Venue": "The Stanford Theater",
  "Series": "Summer 2018",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "5:45 PM",
  "TRT": "",
  "Format": "35mm",
  "Note": "",
  "Film": "The Thin Man",
  "Director": "W. S. Van Dyke",
  "Year": 1934,
  "RATIO": "",
  "Country": "USA",
  "Language": "English",
  "tmdb": ""
  },
  {
  "Venue": "The Stanford Theater",
  "Series": "Summer 2018",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "9:25 PM",
  "TRT": "",
  "Format": "35mm",
  "Note": "",
  "Film": "The Thin Man",
  "Director": "W. S. Van Dyke",
  "Year": 1934,
  "RATIO": "",
  "Country": "USA",
  "Language": "English",
  "tmdb": ""
  },
  {
  "Venue": "The Stanford Theater",
  "Series": "Summer 2018",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "3:50 PM",
  "TRT": "",
  "Format": "35mm",
  "Note": "",
  "Film": "Top Hat",
  "Director": "Mark Sandrich",
  "Year": 1935,
  "RATIO": "",
  "Country": "USA",
  "Language": "English",
  "tmdb": ""
  },
  {
  "Venue": "The Stanford Theater",
  "Series": "Summer 2018",
  "Link": "",
  "Date": "07/14/2018",
  "Showtime": "7:30 PM",
  "TRT": "",
  "Format": "35mm",
  "Note": "",
  "Film": "Top Hat",
  "Director": "Mark Sandrich",
  "Year": 1935,
  "RATIO": "",
  "Country": "USA",
  "Language": "English",
  "tmdb": ""
  }
]

module.exports = exampleData;
