const exampleData = [
  {
    "venue": "Alamo Drafthouse New Mission",
    "series": "",
    "link": "",
    "date": "07/15/2018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Sorry To Bother You",
    "director": "Boots Riley",
    "Year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "Alamo Drafthouse New Mission",
    "series": "",
    "link": "",
    "date": "07/15/2018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Sorry To Bother You",
    "director": "Boots Riley",
    "Year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Popcorn Palace",
    "link": "",
    "date": "07/15/2018",
    "showtime": "10:00 AM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Spirited Away",
    "director": "Hayao Miyazaki",
    "Year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Bergman 100: A Summer Interlude",
    "link": "",
    "date": "07/15/2018",
    "showtime": "5:00 PM",
    "trt": 84,
    "format": "DCP",
    "note": "",
    "film": "Brink of Life",
    "director": "Ingmar Bergman",
    "Year": 1958,
    "ratio": "",
    "country": "Sweden",
    "language": "Swedish",
    "tmdb": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Aki Kaurismäki: Films from the Other Side of Hope",
    "link": "",
    "date": "07/15/2018",
    "showtime": "7:00 PM",
    "trt": 97,
    "format": "",
    "note": "",
    "film": "The Man Without a Past",
    "director": "Aki Kaurismäki",
    "Year": 2002,
    "ratio": "",
    "country": "Finland, France, Germany",
    "language": "Finnish",
    "tmdb": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07/15/2018",
    "showtime": "1:30 PM",
    "trt": 127,
    "format": "DCP",
    "note": "",
    "film": "20,000 Leagues Under the Sea",
    "director": "Richard Fleischer",
    "Year": 1954,
    "ratio": "Scope",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07/15/2018",
    "showtime": "3:50 PM",
    "trt": 104,
    "format": "DCP",
    "note": "",
    "film": "Jason and the Argonauts",
    "director": "Don Chaffey",
    "Year": 1963,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07/15/2018",
    "showtime": "6:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "Year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07/15/2018",
    "showtime": "8:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "Year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "2:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Jitney Elopement",
    "director": "",
    "Year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "11:30 AM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Night Out",
    "director": "",
    "Year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "1:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "In The Park",
    "director": "",
    "Year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "12:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Champion",
    "director": "",
    "Year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "3:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Tramp",
    "director": "",
    "Year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07/15/2018",
    "showtime": "3:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "When The Movies Came from Niles",
    "director": "",
    "Year": 1964,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07/15/2018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ava",
    "director": "Sadaf Foroughi",
    "Year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07/15/2018",
    "showtime": "1:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "Year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07/15/2018",
    "showtime": "8:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "Year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "MiDNiTES FOR MANiACS",
    "link": "",
    "date": "07/15/2018",
    "showtime": "9:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "Double Feature with Milk",
    "film": "Mala Noche",
    "director": "Gus Van Sant",
    "Year": 1988,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "MiDNiTES FOR MANiACS",
    "link": "",
    "date": "07/15/2018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "35mm",
    "note": "10 Year Anniversary \n Double Feature with Mala Noche",
    "film": "Milk",
    "director": "Gus Van Sant",
    "Year": 2008,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07/15/2018",
    "showtime": "1:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Eve's Bayou",
    "director": "Kasi Lemmons",
    "Year": 1997,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07/15/2018",
    "showtime": "4:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Losing Ground",
    "director": "Kathleen Collins",
    "Year": 1982,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07/15/2018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Love Jones",
    "director": "Theodore Witcher",
    "Year": 1997,
    "ratio": "",
    "country": "",
    "language": "",
    "tmdb": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07/15/2018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "Year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07/15/2018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "Year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07/15/2018",
    "showtime": "3:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "Year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07/15/2018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "Year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "tmdb": ""
  }
]

const tomorrow = [  {
  "venue": "BAMPFA",
  "series": "Jacques Becker",
  "link": "",
  "date": "07/14/2018",
  "showtime": "6:00 PM",
  "trt": 110,
  "format": "35mm",
  "note": "Imported Print",
  "film": "Goupi mains-rouges",
  "director": "Jacques Becker",
  "Year": 1943,
  "ratio": "",
  "country": "France",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "BAMPFA",
  "series": "Michelangelo Antonioni",
  "link": "https://bampfa.org/event/le-amiche-5",
  "date": "07/14/2018",
  "showtime": "8:00 PM",
  "trt": 104,
  "format": "35mm",
  "note": "Imported Print",
  "film": "Le Amiche",
  "director": "Michelangelo Antonioni",
  "Year": "",
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Niles Essanay Silent Film Museum",
  "series": "Charlie Chaplin Days",
  "link": "",
  "date": "07/14/2018",
  "showtime": "1:15 PM",
  "trt": "",
  "format": "",
  "note": "with audio commentary by Dan Kamin",
  "film": "One A.M.",
  "director": "",
  "Year": 1915,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Niles Essanay Silent Film Museum",
  "series": "Charlie Chaplin Days",
  "link": "",
  "date": "07/14/2018",
  "showtime": "12:30 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "The Champion",
  "director": "",
  "Year": 1915,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Niles Essanay Silent Film Museum",
  "series": "Charlie Chaplin Days",
  "link": "",
  "date": "07/14/2018",
  "showtime": "7:00 PM",
  "trt": "",
  "format": "",
  "note": "Judy Rosenberg (piano) \\n Preceded by shorts: Chaplin’s Flea Circus (1921), A Night at the Show (1915, Essanay, Los Angeles)",
  "film": "The Kid",
  "director": "",
  "Year": 1921,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Niles Essanay Silent Film Museum",
  "series": "Charlie Chaplin Days",
  "link": "",
  "date": "07/14/2018",
  "showtime": "2:45 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "The Movies Go West",
  "director": "",
  "Year": 1974,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Niles Essanay Silent Film Museum",
  "series": "Charlie Chaplin Days",
  "link": "",
  "date": "07/14/2018",
  "showtime": "3:15 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "The Tramp",
  "director": "",
  "Year": 1915,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Roxie Theater",
  "series": "",
  "link": "",
  "date": "07/14/2018",
  "showtime": "7:00 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Ava",
  "director": "Sadaf Foroughi",
  "Year": 2017,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Roxie Theater",
  "series": "",
  "link": "",
  "date": "07/14/2018",
  "showtime": "5:00 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Jim Gaffigan: Noble Ape",
  "director": "Jeannie Gaffigan",
  "Year": "",
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Roxie Theater",
  "series": "",
  "link": "",
  "date": "07/14/2018",
  "showtime": "4:30 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Perdida",
  "director": "Viviana García-Besné",
  "Year": 2009,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "Roxie Theater",
  "series": "",
  "link": "",
  "date": "07/14/2018",
  "showtime": "7:00 PM",
  "trt": 70,
  "format": "",
  "note": "",
  "film": "Santo Contra Cerebro Del Mal",
  "director": "Joselito Rodriguez",
  "Year": 1961,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "SF MOMA",
  "series": "Black Powers: Reframing Hollywood",
  "link": "",
  "date": "07/14/2018",
  "showtime": "4:00 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Do the Right Thing",
  "director": "Spike Lee",
  "Year": 1989,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "SF MOMA",
  "series": "Black Powers: Reframing Hollywood",
  "link": "",
  "date": "07/14/2018",
  "showtime": "1:00 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Killer of Sheep",
  "director": "Charles Burnett",
  "Year": 1978,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "SF MOMA",
  "series": "Black Powers: Reframing Hollywood",
  "link": "",
  "date": "07/14/2018",
  "showtime": "7:00 PM",
  "trt": "",
  "format": "",
  "note": "",
  "film": "Medicine for Melancholy",
  "director": "Barry Jenkins",
  "Year": 2008,
  "ratio": "",
  "country": "",
  "language": "",
  "tmdb": ""
  },
  {
  "venue": "The Stanford Theater",
  "series": "Summer 2018",
  "link": "",
  "date": "07/14/2018",
  "showtime": "5:45 PM",
  "trt": "",
  "format": "35mm",
  "note": "",
  "film": "The Thin Man",
  "director": "W. S. Van Dyke",
  "Year": 1934,
  "ratio": "",
  "country": "USA",
  "language": "English",
  "tmdb": ""
  },
  {
  "venue": "The Stanford Theater",
  "series": "Summer 2018",
  "link": "",
  "date": "07/14/2018",
  "showtime": "9:25 PM",
  "trt": "",
  "format": "35mm",
  "note": "",
  "film": "The Thin Man",
  "director": "W. S. Van Dyke",
  "Year": 1934,
  "ratio": "",
  "country": "USA",
  "language": "English",
  "tmdb": ""
  },
  {
  "venue": "The Stanford Theater",
  "series": "Summer 2018",
  "link": "",
  "date": "07/14/2018",
  "showtime": "3:50 PM",
  "trt": "",
  "format": "35mm",
  "note": "",
  "film": "Top Hat",
  "director": "Mark Sandrich",
  "Year": 1935,
  "ratio": "",
  "country": "USA",
  "language": "English",
  "tmdb": ""
  },
  {
  "venue": "The Stanford Theater",
  "series": "Summer 2018",
  "link": "",
  "date": "07/14/2018",
  "showtime": "7:30 PM",
  "trt": "",
  "format": "35mm",
  "note": "",
  "film": "Top Hat",
  "director": "Mark Sandrich",
  "Year": 1935,
  "ratio": "",
  "country": "USA",
  "language": "English",
  "tmdb": ""
  }
]



module.exports = exampleData;
