const exampleData = [
  {
    "venue": "BAMPFA",
    "series": "The Luminous Legacy of Greta Garbo",
    "link": "https://bampfa.org/event/camille-1",
    "date": "07012018",
    "showtime": "4:30 PM",
    "trt": 108,
    "format": "DCP",
    "note": "",
    "film": "Camille",
    "director": "George Cukor",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/story-love-affair-1",
    "date": "07012018",
    "showtime": "7:00 PM",
    "trt": 110,
    "format": "35mm",
    "note": "Imported Print",
    "film": "Story of a Love Affair",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Sing-a-long Sound of Music",
    "link": "http://castrotheatre.com/p-list.html#jun29",
    "date": "07012018",
    "showtime": "1:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Sound of Music",
    "director": "Robert Wise",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Sing-a-long Sound of Music",
    "link": "http://castrotheatre.com/p-list.html#jun29",
    "date": "07012018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Sound of Music",
    "director": "Robert Wise",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Spielberg",
    "link": "http://castrotheatre.com/p-list.html#jul03",
    "date": "07032018",
    "showtime": "5:10 PM",
    "trt": "",
    "format": "35mm",
    "note": "Theatrical Cut",
    "film": "Duel",
    "director": "Steven Spielberg",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Spielberg",
    "link": "http://castrotheatre.com/p-list.html#jul03",
    "date": "07032018",
    "showtime": "9:15 PM",
    "trt": "",
    "format": "35mm",
    "note": "Theatrical Cut",
    "film": "Duel",
    "director": "Steven Spielberg",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Spielberg",
    "link": "http://castrotheatre.com/p-list.html#jul03",
    "date": "07032018",
    "showtime": "2:55 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Jaws",
    "director": "Steven Spielberg",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Spielberg",
    "link": "http://castrotheatre.com/p-list.html#jul03",
    "date": "07032018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Jaws",
    "director": "Steven Spielberg",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Limited Engagements & Special Screenings",
    "link": "https://bampfa.org/event/mur-murs-0",
    "date": "07042018",
    "showtime": "5:00 PM",
    "trt": 81,
    "format": "DCP",
    "note": "Digital Restoration",
    "film": "Mur Murs",
    "director": "Agnes Varda",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/red-desert-6",
    "date": "07042018",
    "showtime": "7:00 PM",
    "trt": 117,
    "format": "35mm",
    "note": "",
    "film": "Red Desert",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Bergman 100: A Summer Interlude",
    "link": "",
    "date": "07052018",
    "showtime": "7:00 PM",
    "trt": 99,
    "format": "DCP",
    "note": "",
    "film": "Port of Call",
    "director": "Ingmar Bergman",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Sing-a-long Sound of Music",
    "link": "http://castrotheatre.com/p-list.html#jul05",
    "date": "07052018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Sound of Music",
    "director": "Robert Wise",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Sing-a-long Sound of Music",
    "link": "http://castrotheatre.com/p-list.html#jul05",
    "date": "07062018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Sound of Music",
    "director": "Robert Wise",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07062018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "It Happened One Night",
    "director": "Frank Capra",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07062018",
    "showtime": "5:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07062018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "The Luminous Legacy of Greta Garbo",
    "link": "https://bampfa.org/event/ninotchka-6",
    "date": "07072018",
    "showtime": "8:15 PM",
    "trt": 110,
    "format": "DCP",
    "note": "",
    "film": "Ninotchka",
    "director": "Ernst Lubitsch",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/lady-without-camellias-1",
    "date": "07072018",
    "showtime": "6:00 PM",
    "trt": 105,
    "format": "35mm",
    "note": "",
    "film": "The Lady Without Camellias",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Scary Cow",
    "link": "",
    "date": "07072018",
    "showtime": "2:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Scary Cow 34th Short Film Festival",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "8:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Quiet Place",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "2:10 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "First Reformed",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "9:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "5:50 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "10:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "12:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Isle of Dogs",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Isle of Dogs",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "2:55 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ready Player One",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "4:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Upgrade",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "The Great Stone Face",
    "link": "",
    "date": "07072018",
    "showtime": "7:03 PM",
    "trt": "",
    "format": "",
    "note": "Frederick Hodges (Piano) Preceded by shorts: A Ten-Minute Egg (1924, Hal Roach) Charley Chase Knight of the Trail (1915, Kay-Bee) William S. Hart",
    "film": "Square Deal Sanderson",
    "director": "William S. Hart, Lambert Hillyer",
    "year": 1919,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "7:00 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "9:00 PM",
    "trt": 127,
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "Ari Aster",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "9:00 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "RBG",
    "director": "Julie Cohen, Betsy West",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07072018",
    "showtime": "7:00 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07072018",
    "showtime": "3:55 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "It Happened One Night",
    "director": "Frank Capra",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07072018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "It Happened One Night",
    "director": "Frank Capra",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07072018",
    "showtime": "5:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07072018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/i-vinti-1",
    "date": "07082018",
    "showtime": "7:00 PM",
    "trt": 110,
    "format": "DCP",
    "note": "",
    "film": "I Vinti",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Aki Kaurismäki: Films from the Other Side of Hope",
    "link": "",
    "date": "07082018",
    "showtime": "5:15 PM",
    "trt": 74,
    "format": "",
    "note": "",
    "film": "The Match Factory Girl",
    "director": "Aki Kaurismäki",
    "year": 1990,
    "ratio": "",
    "country": "Finland, Sweden",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Sunday Summer Cinema",
    "link": "",
    "date": "07082018",
    "showtime": "4:00 PM",
    "trt": 133,
    "format": "DCP",
    "note": "At Outdoor Screen",
    "film": "The Red Shoes",
    "director": "Michael Powell, Emeric Pressburger",
    "year": 1948,
    "ratio": "",
    "country": "United Kingdom",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Triple Feature: The Godfather Trilogy",
    "link": "http://castrotheatre.com/p-list.html#jul08",
    "date": "07082018",
    "showtime": "1:00 PM",
    "trt": "",
    "format": "4K DCP",
    "note": "with Intermission",
    "film": "The Godfather",
    "director": "Francis Ford Coppola",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Triple Feature: The Godfather Trilogy",
    "link": "http://castrotheatre.com/p-list.html#jul08",
    "date": "07082018",
    "showtime": "4:10 PM",
    "trt": "",
    "format": "4K DCP",
    "note": "with Intermission",
    "film": "The Godfather Part II",
    "director": "Francis Ford Coppola",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Triple Feature: The Godfather Trilogy",
    "link": "http://castrotheatre.com/p-list.html#jul08",
    "date": "07082018",
    "showtime": "8:00 PM",
    "trt": "",
    "format": "4K DCP",
    "note": "",
    "film": "The Godfather Part III",
    "director": "Francis Ford Coppola",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Quiet Place",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "2:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "9:10 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "12:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "5:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "6:55 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Isle of Dogs",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "12:50 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ready Player One",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "9:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Upgrade",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "3:00 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "7:15 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "2:15 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "RBG",
    "director": "Julie Cohen, Betsy West",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "9:15 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "RBG",
    "director": "Julie Cohen, Betsy West",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "5:00 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "Stray Dog",
    "director": "Debra Granik",
    "year": 2014,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "6:30 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "4:30 PM",
    "trt": 83,
    "format": "",
    "note": "",
    "film": "Westwood: Punk, Icon, Activist",
    "director": "Lorna Tucker",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07082018",
    "showtime": "8:20 PM",
    "trt": 83,
    "format": "",
    "note": "",
    "film": "Westwood: Punk, Icon, Activist",
    "director": "Lorna Tucker",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07082018",
    "showtime": "3:55 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "It Happened One Night",
    "director": "Frank Capra",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07082018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "It Happened One Night",
    "director": "Frank Capra",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07082018",
    "showtime": "5:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07082018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Palm Beach Story",
    "director": "Preston Sturges",
    "year": 1942,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul09",
    "date": "07092018",
    "showtime": "7:45 PM",
    "trt": 184,
    "format": "DCP",
    "note": "",
    "film": "Barry Lyndon",
    "director": "Stanley Kubrick",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul09",
    "date": "07092018",
    "showtime": "6:00 PM",
    "trt": 93,
    "format": "DCP",
    "note": "",
    "film": "Filmworker",
    "director": "Tony Zierra",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "9:10 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Quiet Place",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "6:50 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "8:55 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Upgrade",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "7:00 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "9:05 PM",
    "trt": 127,
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "Ari Aster",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "7:00 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07092018",
    "showtime": "9:00 PM",
    "trt": 83,
    "format": "",
    "note": "",
    "film": "Westwood: Punk, Icon, Activist",
    "director": "Lorna Tucker",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Cameo Theater",
    "series": "Science on Screen",
    "link": "",
    "date": "07102018",
    "showtime": "7:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Robot & Frank",
    "director": "Jake Schreier",
    "year": 2012,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Kubrick",
    "link": "http://castrotheatre.com/p-list.html#jul10",
    "date": "07102018",
    "showtime": "9:35 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Full Metal Jacket",
    "director": "Stanley Kubrick",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Kubrick",
    "link": "http://castrotheatre.com/p-list.html#jul10",
    "date": "07102018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Shining",
    "director": "Stanley Kubrick",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "First Reformed",
    "director": "Paul Schrader",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "9:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "07102018",
    "showtime": "6:35 PM",
    "trt": 56,
    "format": "",
    "note": "co-presented by the Berkeley Film Foundation and featuring filmmaker Q&A",
    "film": "The Pushouts",
    "director": "Katie Galloway, Dawn Valadez",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "9:00 PM",
    "trt": 141,
    "format": "",
    "note": "",
    "film": "Attack on Titan: Roar of Awakening",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "Japanese with English Subtitles",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "Docunight",
    "link": "",
    "date": "07102018",
    "showtime": "5:00 PM",
    "trt": 74,
    "format": "",
    "note": "",
    "film": "Exilic Trilogy",
    "director": "Arsalan Baraheni",
    "year": 2015,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "9:00 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "RBG",
    "director": "Julie Cohen, Betsy West",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07102018",
    "showtime": "7:00 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07102018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Dinner at Eight",
    "director": "George Cukor",
    "year": 1933,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07102018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07102018",
    "showtime": "9:35 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Bergman 100: A Summer Interlude",
    "link": "",
    "date": "07112018",
    "showtime": "7:00 PM",
    "trt": 107,
    "format": "",
    "note": "",
    "film": "Secrets of Women",
    "director": "Ingmar Bergman",
    "year": 1952,
    "ratio": "",
    "country": "Sweden",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul11",
    "date": "07112018",
    "showtime": "6:00 PM",
    "trt": "",
    "format": "DCP",
    "note": "",
    "film": "Filmworker",
    "director": "Tony Zierra",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Quiet Place",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "6:50 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Isle of Dogs",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "8:35 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ready Player One",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "9:10 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Upgrade",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "6:45 PM",
    "trt": 141,
    "format": "",
    "note": "",
    "film": "Attack on Titan: Roar of Awakening",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "English Dubbed",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "9:35 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "9:00 PM",
    "trt": 98,
    "format": "",
    "note": "",
    "film": "RBG",
    "director": "Julie Cohen, Betsy West",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07112018",
    "showtime": "7:00 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07112018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Dinner at Eight",
    "director": "George Cukor",
    "year": 1933,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07112018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07112018",
    "showtime": "9:35 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Limited Engagements & Special Screenings",
    "link": "",
    "date": "07122018",
    "showtime": "7:00 PM",
    "trt": 195,
    "format": "DCP",
    "note": "East Bay Premiere",
    "film": "My Journey Through French Cinema",
    "director": "Bertrand Tavernier",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jun12",
    "date": "07122018",
    "showtime": "7:00 PM",
    "trt": 87,
    "format": "DCP",
    "note": "4K Restoration 5.1 Sound Mix",
    "film": "A Hard Day's Night",
    "director": "",
    "year": 1964,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul11",
    "date": "07112018",
    "showtime": "7:45 PM",
    "trt": 159,
    "format": "35mm",
    "note": "",
    "film": "Eyes Wide Shut",
    "director": "Stanley Kubrick",
    "year": 1999,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jun12",
    "date": "07122018",
    "showtime": "8:40 PM",
    "trt": 113,
    "format": "DCP",
    "note": "",
    "film": "Sgt. Pepper's Lonely Hearts Club Band",
    "director": "",
    "year": 1978,
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "First Reformed",
    "director": "Paul Schrader",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "8:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hereditary",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "6:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hotel Artemis",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "9:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Legend",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "4:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Upgrade",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "9:35 PM",
    "trt": 90,
    "format": "",
    "note": "Subtitled",
    "film": "Fireworks",
    "director": "Nobuyuki Takeuchi, Akiyuki Shinbô",
    "year": 2017,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "7:00 PM",
    "trt": 80,
    "format": "",
    "note": "",
    "film": "That Summer",
    "director": "Göran Olsson",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07122018",
    "showtime": "4:30 PM",
    "trt": 83,
    "format": "",
    "note": "",
    "film": "Westwood: Punk, Icon, Activist",
    "director": "Lorna Tucker",
    "year": 2018,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07122018",
    "showtime": "6:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Body and Soul",
    "director": "Oscar Micheaux",
    "year": 1925,
    "ratio": "",
    "country": "USA",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07122018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Dinner at Eight",
    "director": "George Cukor",
    "year": 1933,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07122018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07122018",
    "showtime": "9:35 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Holiday",
    "director": "George Cukor",
    "year": 1938,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Aki Kaurismäki: Films from the Other Side of Hope",
    "link": "",
    "date": "07132018",
    "showtime": "8:30 PM",
    "trt": 100,
    "format": "",
    "note": "",
    "film": "La vie de Bohème",
    "director": "Aki Kaurismäki",
    "year": 1992,
    "ratio": "",
    "country": "Finland, France",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "The Luminous Legacy of Greta Garbo",
    "link": "https://bampfa.org/event/two-faced-woman-0",
    "date": "07132018",
    "showtime": "6:30 PM",
    "trt": 88,
    "format": "35mm",
    "note": "",
    "film": "Two-Faced Woman",
    "director": "George Cukor",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Moana Sing-Along",
    "link": "http://castrotheatre.com/p-list.html#jun13",
    "date": "07132018",
    "showtime": "4:30 PM",
    "trt": 120,
    "format": "DCP",
    "note": "Hosted by Sara Moore & Laurie Bushman",
    "film": "Moana",
    "director": "",
    "year": 2016,
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul14",
    "date": "07132018",
    "showtime": "7:00 PM",
    "trt": 129,
    "format": "35mm",
    "note": "",
    "film": "The Bad Seed",
    "director": "",
    "year": 1956,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "http://castrotheatre.com/p-list.html#jul14",
    "date": "07132018",
    "showtime": "9:20 PM",
    "trt": 111,
    "format": "DCP",
    "note": "",
    "film": "The Omen",
    "director": "",
    "year": 1976,
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07132018",
    "showtime": "10:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Friday the 13th: The Final Chapter",
    "director": "Joseph Zito",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07132018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ava",
    "director": "Sadaf Foroughi",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07132018",
    "showtime": "5:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07132018",
    "showtime": "9:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07132018",
    "showtime": "6:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Chameleon Street",
    "director": "Wendell B. Harris",
    "year": 1989,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07132018",
    "showtime": "8:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Get Out",
    "director": "Jordan Peele",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07132018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07132018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07132018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Yerba Buena Center for the Arts",
    "series": "Special Presentation",
    "link": "",
    "date": "07132018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "A benefit salon for THE CELINE ARCHIVE.",
    "film": "The Celine Archive",
    "director": "Celine Parreñas Shimizu",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Jacques Becker",
    "link": "",
    "date": "07142018",
    "showtime": "6:00 PM",
    "trt": 110,
    "format": "35mm",
    "note": "Imported Print",
    "film": "Goupi mains-rouges",
    "director": "Jacques Becker",
    "year": 1943,
    "ratio": "",
    "country": "France",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/le-amiche-5",
    "date": "07142018",
    "showtime": "8:00 PM",
    "trt": 104,
    "format": "35mm",
    "note": "Imported Print",
    "film": "Le Amiche",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07142018",
    "showtime": "1:15 PM",
    "trt": "",
    "format": "",
    "note": "with audio commentary by Dan Kamin",
    "film": "One A.M.",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07142018",
    "showtime": "12:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Champion",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07142018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "Judy Rosenberg (piano) Preceded by shorts: Chaplin’s Flea Circus (1921), A Night at the Show (1915, Essanay, Los Angeles)",
    "film": "The Kid",
    "director": "",
    "year": 1921,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07142018",
    "showtime": "2:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Movies Go West",
    "director": "",
    "year": 1974,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07142018",
    "showtime": "3:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Tramp",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07142018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ava",
    "director": "Sadaf Foroughi",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07142018",
    "showtime": "5:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07142018",
    "showtime": "4:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Perdida",
    "director": "Viviana García-Besné",
    "year": 2009,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07142018",
    "showtime": "7:00 PM",
    "trt": 70,
    "format": "",
    "note": "",
    "film": "Santo Contra Cerebro Del Mal",
    "director": "Joselito Rodriguez",
    "year": 1961,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07142018",
    "showtime": "4:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Do the Right Thing",
    "director": "Spike Lee",
    "year": 1989,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07142018",
    "showtime": "1:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Killer of Sheep",
    "director": "Charles Burnett",
    "year": 1978,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07142018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Medicine for Melancholy",
    "director": "Barry Jenkins",
    "year": 2008,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07142018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07142018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07142018",
    "showtime": "3:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07142018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Alamo Drafthouse New Mission",
    "series": "",
    "link": "",
    "date": "07152018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Sorry To Bother You",
    "director": "Boots Riley",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Alamo Drafthouse New Mission",
    "series": "",
    "link": "",
    "date": "07152018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Sorry To Bother You",
    "director": "Boots Riley",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Popcorn Palace",
    "link": "",
    "date": "07152018",
    "showtime": "10:00 AM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Spirited Away",
    "director": "Hayao Miyazaki",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Bergman 100: A Summer Interlude",
    "link": "",
    "date": "07152018",
    "showtime": "5:00 PM",
    "trt": 84,
    "format": "DCP",
    "note": "",
    "film": "Brink of Life",
    "director": "Ingmar Bergman",
    "year": 1958,
    "ratio": "",
    "country": "Sweden",
    "language": "Swedish",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Aki Kaurismäki: Films from the Other Side of Hope",
    "link": "",
    "date": "07152018",
    "showtime": "7:00 PM",
    "trt": 97,
    "format": "",
    "note": "",
    "film": "The Man Without a Past",
    "director": "Aki Kaurismäki",
    "year": 2002,
    "ratio": "",
    "country": "Finland, France, Germany",
    "language": "Finnish",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07152018",
    "showtime": "1:30 PM",
    "trt": 127,
    "format": "DCP",
    "note": "",
    "film": "20,000 Leagues Under the Sea",
    "director": "Richard Fleischer",
    "year": 1954,
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07152018",
    "showtime": "3:50 PM",
    "trt": 104,
    "format": "DCP",
    "note": "",
    "film": "Jason and the Argonauts",
    "director": "Don Chaffey",
    "year": 1963,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07152018",
    "showtime": "6:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07152018",
    "showtime": "8:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "2:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Jitney Elopement",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "11:30 AM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Night Out",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "1:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "In The Park",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "12:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Champion",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "3:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Tramp",
    "director": "",
    "year": 1915,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Niles Essanay Silent Film Museum",
    "series": "Charlie Chaplin Days",
    "link": "",
    "date": "07152018",
    "showtime": "3:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "When The Movies Came from Niles",
    "director": "",
    "year": 1964,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07152018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Ava",
    "director": "Sadaf Foroughi",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07152018",
    "showtime": "1:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "",
    "link": "",
    "date": "07152018",
    "showtime": "8:45 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Jim Gaffigan: Noble Ape",
    "director": "Jeannie Gaffigan",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "MiDNiTES FOR MANiACS",
    "link": "",
    "date": "07152018",
    "showtime": "9:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Mala Noche",
    "director": "Gus Van Sant",
    "year": 1988,
    "ratio": "",
    "country": "",
    "language": "Double Feature with Milk",
    "": ""
  },
  {
    "venue": "Roxie Theater",
    "series": "MiDNiTES FOR MANiACS",
    "link": "",
    "date": "07152018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Milk",
    "director": "Gus Van Sant",
    "year": 2008,
    "ratio": "",
    "country": "",
    "language": "10 Year Anniversary, Double Feature with Mala Noche",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07152018",
    "showtime": "1:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Eve's Bayou",
    "director": "Kasi Lemmons",
    "year": 1997,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07152018",
    "showtime": "4:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Losing Ground",
    "director": "Kathleen Collins",
    "year": 1982,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "SF MOMA",
    "series": "Black Powers: Reframing Hollywood",
    "link": "",
    "date": "07152018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Love Jones",
    "director": "Theodore Witcher",
    "year": 1997,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07152018",
    "showtime": "5:45 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07152018",
    "showtime": "9:25 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "The Thin Man",
    "director": "W. S. Van Dyke",
    "year": 1934,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07152018",
    "showtime": "3:50 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "The Stanford Theater",
    "series": "Summer 2018",
    "link": "",
    "date": "07152018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "35mm",
    "note": "",
    "film": "Top Hat",
    "director": "Mark Sandrich",
    "year": 1935,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "AniMonday",
    "link": "",
    "date": "07162018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Spirited Away",
    "director": "Hayao Miyazaki",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Cameo Theater",
    "series": "Sing Along",
    "link": "",
    "date": "07162018",
    "showtime": "7:45 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07162018",
    "showtime": "6:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07162018",
    "showtime": "8:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07172018",
    "showtime": "6:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07172018",
    "showtime": "8:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "07172018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "co-presented by Reel Black Films",
    "film": "Black Fatherhood",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Rewind Wednesday",
    "link": "",
    "date": "07182018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "",
    "note": "with Beavis & Butthead episodes",
    "film": "Wayne's World",
    "director": "Penelope Spheeris",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07182018",
    "showtime": "6:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Yellow Submarine 50th Anniversary",
    "link": "",
    "date": "07182018",
    "showtime": "8:00 PM",
    "trt": 85,
    "format": "DCP",
    "note": "50th Anniversary 4K Restoration",
    "film": "Yellow Submarine",
    "director": "George Dunning",
    "year": 1968,
    "ratio": "",
    "country": "United Kingdom",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/il-grido-5",
    "date": "07192018",
    "showtime": "7:00 PM",
    "trt": 107,
    "format": "35mm",
    "note": "Imported Print",
    "film": "Il Grido",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "38th San Francisco Jewish Film Festival",
    "link": "",
    "date": "07192018",
    "showtime": "6:30 PM",
    "trt": 84,
    "format": "",
    "note": "Bay Area Premiere Opening Night",
    "film": "Love, Gilda",
    "director": "Lisa Dapolito",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07192018",
    "showtime": "9:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Matrix",
    "director": "The Wachowskis",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "6:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "20 Feet from Stardom",
    "director": "Morgan Nevile",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "8:25 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Beyoncé: Lemonade",
    "director": "Beyoncé Knowles-Carter, Kahlil Joseph, Todd Tourso",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "5:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hamilton's America",
    "director": "Alex Horwitz",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "4:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Happy Feet",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "10:05 PM",
    "trt": 101,
    "format": "",
    "note": "",
    "film": "Labyrinth",
    "director": "Jim Henson",
    "year": 1986,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "7:00 PM",
    "trt": 94,
    "format": "",
    "note": "",
    "film": "Little Shop of Horrors",
    "director": "",
    "year": 1986,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07202018",
    "showtime": "9:25 PM",
    "trt": 147,
    "format": "",
    "note": "",
    "film": "Straight Outta Compton",
    "director": "F. Gary Gray",
    "year": 2015,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/blow-6",
    "date": "07212018",
    "showtime": "6:00 PM",
    "trt": 110,
    "format": "DCP",
    "note": "Digital Restoration",
    "film": "Blow-Up",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "12:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Hard Day's Night",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "7:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Beyoncé: Lemonade",
    "director": "Beyoncé Knowles-Carter, Kahlil Joseph, Todd Tourso",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "3:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Blue Hawaii",
    "director": "Norman Taurog",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "12:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Happy Feet",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "4:10 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Pitch Perfect",
    "director": "Jason Moore",
    "year": 2012,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "9:25 PM",
    "trt": 88,
    "format": "DCP",
    "note": "",
    "film": "Stop Making Sense",
    "director": "Jonathan Demme",
    "year": 1984,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "9:00 PM",
    "trt": 133,
    "format": "DCP",
    "note": "co-presented by KPFA",
    "film": "The Blues Brothers",
    "director": "John Landis",
    "year": 1980,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Sing Along",
    "link": "",
    "date": "07212018",
    "showtime": "5:15 PM",
    "trt": 105,
    "format": "",
    "note": "",
    "film": "The Greatest Showman",
    "director": "Michael Gracey",
    "year": 2017,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "2:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Sapphires",
    "director": "Wayne Blair",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07212018",
    "showtime": "6:45 PM",
    "trt": 100,
    "format": "",
    "note": "",
    "film": "Under the Cherry Moon",
    "director": "Prince",
    "year": 1986,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "4:15 PM",
    "trt": 91,
    "format": "",
    "note": "",
    "film": "20 Feet from Stardom",
    "director": "Morgan Nevile",
    "year": 2013,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "2:50 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "A Hard Day's Night",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "9:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Beyoncé: Lemonade",
    "director": "Beyoncé Knowles-Carter, Kahlil Joseph, Todd Tourso",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "7:15 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Breakin'",
    "director": "Joe Silberg",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "4:50 PM",
    "trt": 115,
    "format": "",
    "note": "",
    "film": "Grace Jones: Bloodlight and Bami",
    "director": "Sophie Fiennes",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "2:20 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Hamilton's America",
    "director": "Alex Horwitz",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "12:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Happy Feet",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "6:15 PM",
    "trt": 94,
    "format": "",
    "note": "co-presented by KPFA",
    "film": "Little Shop of Horrors",
    "director": "",
    "year": 1986,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07222018",
    "showtime": "8:40 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Bodyguard",
    "director": "Mick Jackson",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07232018",
    "showtime": "9:10 PM",
    "trt": 86,
    "format": "",
    "note": "",
    "film": "Here to Be Heard: The Story of the Slits",
    "director": "",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07232018",
    "showtime": "7:00 PM",
    "trt": 101,
    "format": "",
    "note": "",
    "film": "Labyrinth",
    "director": "Jim Henson",
    "year": 1986,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07232018",
    "showtime": "8:40 PM",
    "trt": 101,
    "format": "",
    "note": "",
    "film": "Labyrinth",
    "director": "Jim Henson",
    "year": 1986,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07232018",
    "showtime": "6:30 PM",
    "trt": 103,
    "format": "",
    "note": "",
    "film": "The Sapphires",
    "director": "Wayne Blair",
    "year": 2012,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07242018",
    "showtime": "9:30 PM",
    "trt": 64,
    "format": "",
    "note": "",
    "film": "Beyoncé: Lemonade",
    "director": "Beyoncé Knowles-Carter, Kahlil Joseph, Todd Tourso",
    "year": 2016,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "07242018",
    "showtime": "7:00 PM",
    "trt": 115,
    "format": "",
    "note": "",
    "film": "Grace Jones: Bloodlight and Bami",
    "director": "Sophie Fiennes",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07242018",
    "showtime": "6:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Pitch Perfect",
    "director": "Jason Moore",
    "year": 2012,
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07242018",
    "showtime": "9:00 PM",
    "trt": 100,
    "format": "",
    "note": "",
    "film": "Under the Cherry Moon",
    "director": "Prince",
    "year": 1986,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Super Shangri-La Show",
    "link": "",
    "date": "07252018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Barbary Coast",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07252018",
    "showtime": "6:50 PM",
    "trt": 91,
    "format": "",
    "note": "",
    "film": "20 Feet from Stardom",
    "director": "Morgan Nevile",
    "year": 2013,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07252018",
    "showtime": "9:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Out of Focus Video Festival",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07252018",
    "showtime": "9:30 PM",
    "trt": 88,
    "format": "DCP",
    "note": "",
    "film": "Stop Making Sense",
    "director": "Jonathan Demme",
    "year": 1984,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07252018",
    "showtime": "6:30 PM",
    "trt": 147,
    "format": "",
    "note": "",
    "film": "Straight Outta Compton",
    "director": "F. Gary Gray",
    "year": 2015,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Music Movie Monthly",
    "link": "",
    "date": "07262018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "Stop Making Sense",
    "director": "Jonathan Demme",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07262018",
    "showtime": "5:30 PM",
    "trt": 64,
    "format": "",
    "note": "",
    "film": "Beyoncé: Lemonade",
    "director": "Beyoncé Knowles-Carter, Kahlil Joseph, Todd Tourso",
    "year": 2016,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07262018",
    "showtime": "4:00 PM",
    "trt": 102,
    "format": "DCP",
    "note": "",
    "film": "Blue Hawaii",
    "director": "Norman Taurog",
    "year": 1961,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "",
    "date": "07262018",
    "showtime": "9:30 PM",
    "trt": 90,
    "format": "DCP",
    "note": "",
    "film": "Breakin'",
    "director": "Joe Silberg",
    "year": 1984,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Parkway Classics",
    "link": "",
    "date": "07262018",
    "showtime": "9:00 PM",
    "trt": 133,
    "format": "DCP",
    "note": "co-presented by KPFA",
    "film": "The Blues Brothers",
    "director": "John Landis",
    "year": 1980,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "",
    "link": "https://ticketing.us.veezi.com/purchase/6104?siteToken=P5WXdOEJ3Eq2eHbZHTAtbg%3D%3D",
    "date": "07262018",
    "showtime": "6:15 PM",
    "trt": 129,
    "format": "DCP",
    "note": "",
    "film": "The Bodyguard",
    "director": "Mick Jackson",
    "year": 1992,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Sing Along",
    "link": "",
    "date": "07262018",
    "showtime": "7:10 PM",
    "trt": 105,
    "format": "",
    "note": "",
    "film": "The Greatest Showman",
    "director": "Michael Gracey",
    "year": 2017,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Cult Night",
    "link": "",
    "date": "07272018",
    "showtime": "10:30 PM",
    "trt": 96,
    "format": "DCP",
    "note": "",
    "film": "Tremors",
    "director": "Ron Underwood",
    "year": 1990,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "BAMPFA",
    "series": "Michelangelo Antonioni",
    "link": "https://bampfa.org/event/zabriskie-point-6",
    "date": "07282018",
    "showtime": "8:00 PM",
    "trt": 112,
    "format": "35mm",
    "note": "",
    "film": "Zabriskie Point",
    "director": "Michelangelo Antonioni",
    "year": "",
    "ratio": "Scope",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Special Presentation",
    "link": "",
    "date": "07282018",
    "showtime": "3:00 PM",
    "trt": 138,
    "format": "DCP",
    "note": "co-presented by KPFA",
    "film": "All The President's Men",
    "director": "Alan J. Pakula",
    "year": 1976,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Outdoor Movie Night",
    "link": "",
    "date": "07282018",
    "showtime": "9:00 PM",
    "trt": 110,
    "format": "DCP",
    "note": "co-presented by Drake's Dealership",
    "film": "Grease",
    "director": "Randal Kleiser",
    "year": 1978,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Party at the Parkway",
    "link": "",
    "date": "07292018",
    "showtime": "9:00 PM",
    "trt": 119,
    "format": "",
    "note": "Subtitled",
    "film": "Howl's Moving Castle",
    "director": "Hayao Miyazaki",
    "year": 2004,
    "ratio": "",
    "country": "Japan",
    "language": "Japanese",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07312018",
    "showtime": "8:35 PM",
    "trt": 113,
    "format": "DCP",
    "note": "",
    "film": "First Reformed",
    "director": "Paul Schrader",
    "year": 2017,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "Castro Theater",
    "series": "Double Feature",
    "link": "",
    "date": "07312018",
    "showtime": "7:00 PM",
    "trt": 81,
    "format": "DCP",
    "note": "4K Restoration",
    "film": "The Passion of Joan of Arc",
    "director": "Carl Dreyer",
    "year": 1928,
    "ratio": "",
    "country": "France",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "07312018",
    "showtime": "7:00 PM",
    "trt": 66,
    "format": "",
    "note": "co-presented by Lucky 420 and featuring a post-film discussion",
    "film": "Mrs. Judo: Be Strong, Be Gentle, Be Beautiful",
    "director": "Yuriko Gamo Romer",
    "year": 2012,
    "ratio": "",
    "country": "Japan",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Animation K.O.",
    "link": "",
    "date": "08022018",
    "showtime": "9:30 PM",
    "trt": 77,
    "format": "DCP",
    "note": "",
    "film": "A Town Called Panic",
    "director": "Stéphane Aubier, Vincent Patar",
    "year": 2009,
    "ratio": "",
    "country": "France",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Throwback Theater",
    "link": "",
    "date": "08032018",
    "showtime": "9:30 PM",
    "trt": 109,
    "format": "DCP",
    "note": "co-presented by Reel Black Films",
    "film": "The Last Dragon",
    "director": "Michael Schultz",
    "year": 1985,
    "ratio": "",
    "country": "",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "Rahsaan Roland Kirk Birthday Bash",
    "link": "",
    "date": "08072018",
    "showtime": "7:00 PM",
    "trt": "",
    "format": "",
    "note": "",
    "film": "The Case of the Three Sided Dream",
    "director": "",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "08072018",
    "showtime": "7:00 PM",
    "trt": 56,
    "format": "",
    "note": "co-presented by the Berkeley Film Foundation and featuring filmmaker Q&A",
    "film": "The Pushouts",
    "director": "Katie Galloway, Dawn Valadez",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Parkway Classics",
    "link": "",
    "date": "08092018",
    "showtime": "9:30 PM",
    "trt": 93,
    "format": "DCP",
    "note": "",
    "film": "The Dark Crystal",
    "director": "Jim Henson",
    "year": 1982,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Doc Night",
    "link": "",
    "date": "08142018",
    "showtime": "6:45 PM",
    "trt": 75,
    "format": "",
    "note": "co-presented by UnCommon Law and featuring a post-film discussion",
    "film": "The Feminist on Cell Block Y",
    "director": "Contessa Gayles",
    "year": 2018,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Party at the Parkway",
    "link": "",
    "date": "08192018",
    "showtime": "3:00 PM",
    "trt": 128,
    "format": "",
    "note": "",
    "film": "La La Land",
    "director": "Damien Chazelle",
    "year": 2016,
    "ratio": "",
    "country": "USA",
    "language": "English",
    "": ""
  },
  {
    "venue": "New Parkway Theater",
    "series": "Special Presentation",
    "link": "",
    "date": "08212018",
    "showtime": "7:00 PM",
    "trt": 104,
    "format": "",
    "note": "co-presented by TIGRA and featuring a post-film discussion",
    "film": "The Organizer",
    "director": "Nick Taylor, Joey Carey",
    "year": 2017,
    "ratio": "",
    "country": "",
    "language": "English",
    "": ""
  },
  {
    "venue": "Balboa Theatre",
    "series": "",
    "link": "",
    "date": "08302018",
    "showtime": "7:30 PM",
    "trt": "",
    "format": "",
    "note": "After film Q&A w/ director Jason Blackmore.",
    "film": "Records Collecting Dust II",
    "director": "Jason Blackmore",
    "year": "",
    "ratio": "",
    "country": "",
    "language": "",
    "": ""
  }
]


module.exports = exampleData;
